### ISSUE TITLE
The error still exists

### ISSUE THREAD

**Issue by 123qwqeq** [MoriyaShiine/anthropophagy#10]
### Mod version

1.20—2

### A description of the issue

the netherite knit has been fixed
just like the last time flesh will not fall this problem still exists the other knives have not been repaired yet 

https://github.com/MoriyaShiine/anthropophagy/assets/138661199/a9621bda-b74b-48b8-b518-206412af4e65

**Comment by MoriyaShiine** [comment]
Unable to reproduce, seems to work fine

https://github.com/MoriyaShiine/anthropophagy/assets/45156123/7e418ed0-2722-4d4d-b0c9-109f26136de4
