### ISSUE TITLE
Sorry, but there's a problem with wooden and gold. They're useless

### ISSUE THREAD

**Issue by 123qwqeq** [MoriyaShiine/anthropophagy#11]
### Mod version

1.20—2

### A description of the issue

Wooden and gold pocket knives have problems

**Comment by MoriyaShiine** [comment]
This isn't very descriptive at all. Can you elaborate?

**Comment by 123qwqeq** [comment]
https://github.com/MoriyaShiine/anthropophagy/assets/138661199/d4033966-1297-4037-aa7c-d8912053d55e


https://github.com/MoriyaShiine/anthropophagy/assets/138661199/9088f4d3-2130-4484-aeee-abdd955b4a24

can your see？ no meat
