### ISSUE TITLE
Eating Bug?

### ISSUE THREAD

**Issue by KXIIIS** [MoriyaShiine/anthropophagy#2]
I'm not sure if this is a bug or not, but I've eaten quite a lot of cooked human flesh. However, when I try to eat literally anything else i.e vanilla food, modded food, etc. my hunger doesn't get restored. It only gets restored by cooked human flesh. Is it that once you eat human flesh, that's the only thing you can eat after or is this a bug? Thanks!

**Comment by MoriyaShiine** [comment]
This is intentional. Once you reach a certain wendigo level, human flesh is the only thing that can sate your appetite

**Comment by KXIIIS** [comment]
Ah, okay. That's actually awesome. Thanks for the response!
