### ISSUE TITLE
Game crashes on launch with no other mods

### ISSUE THREAD

**Issue by lukec3131** [MoriyaShiine/anthropophagy#3]
<img width="884" alt="Screenshot 2020-07-30 at 21 03 05" src="https://user-images.githubusercontent.com/69015053/88969015-1b257600-d2a8-11ea-88b8-7fef0dec06b7.png">

**Comment by MoriyaShiine** [comment]
I'm gonna need a crash log or otherwise I can't do much.

**Comment by MoriyaShiine** [comment]
Closed due to no response in over a month.
