### ISSUE TITLE
It didnt open

### ISSUE THREAD

**Issue by Crocbot04** [MoriyaShiine/anthropophagy#4]
When i openned it said "Could not find required mod: wendigoism requires {cotton-config @ [>=1.0.0-rc.1]}" i have other mods installed mby cuz of dat it aint working but i dunno mby i just stupid pls reply :D

**Comment by CyberFeast2K** [comment]
I have the same issue. Here’s the log, it didn’t give me a crash report https://pastebin.pl/view/81ea42d6.

**Comment by MoriyaShiine** [comment]
Install Cotton. Can't believe I didn't see this issue lol, thanks github for not emailing me

**Comment by CyberFeast2K** [comment]
Cotton isn’t available for 1.16.2 from what I see or does the 1.16.1 version work with 1.16.2?

**Comment by MoriyaShiine** [comment]
Yes.

**Comment by CyberFeast2K** [comment]
Oh ok. Thank you.
