### ISSUE TITLE
Knifes do nothing

### ISSUE THREAD

**Issue by ChristianKilduff** [MoriyaShiine/anthropophagy#7]
This mod has very little info on how to use, but from the curseforge I tried to use the knife, then tried to look through the code and cannot understand what the knife is supposed to do. When I attack a player or a villager with the knife, or even kill, they do not drop any flesh. The self attack feature with shift right clicking also appears to do nothing but hurt myself. The only way of obtaining flesh that I have found was by either having a player or villagers be attacked by a piglutton.

**Comment by MoriyaShiine** [comment]
Version? I can't do anything without that

**Comment by ChristianKilduff** [comment]
> Version? I can't do anything without that

1.18.1, I could be misunderstanding how the mod works, how is one meant to obtain flesh from entities using knifes. My friend murdered me with I knife, and nothing dropped in the swings nor the death. I tried a netherite knife with sharpness 5 (the config said something about damage for guaranteed flesh) and nothing.

**Comment by MoriyaShiine** [comment]
Thanks, after looking I've found I am incredibly intelligent and am searching for a path that doesn't exist; expect a CurseForge release in a few minutes

**Comment by ChristianKilduff** [comment]
> Thanks, after looking I've found I am incredibly intelligent and am searching for a path that doesn't exist; expect a CurseForge release in a few minutes

o, awesome!! I wasnt expecting such quick responses <3
