### ISSUE TITLE
No trophies

### ISSUE THREAD

**Issue by 123qwqeq** [MoriyaShiine/anthropophagy#9]
### Mod version

1.20.1

### A description of the issue

Attacks by creatures in the mod can drop loot normally
but the player cannot

**Comment by MoriyaShiine** [comment]
I'm not sure what this means, can you elaborate?

**Comment by 123qwqeq** [comment]
https://github.com/MoriyaShiine/anthropophagy/assets/138661199/68495fc4-87be-43e0-be72-43824168fc53

**Comment by MoriyaShiine** [comment]
It's chance based on how much damage you deal, does it *never* work or are you just unlucky

**Comment by MoriyaShiine** [comment]
Okay I realized I changed what tag I use and didn't update the code to reflect it
